### ISSUE TITLE
Can not connect to Wifi 5GHz

### ISSUE THREAD

**Issue by tmkst2607** [khoih-prog/WiFiWebServer_RTL8720#1]
@khoih-prog I am developing on RTL8720DN then find your document. I'm very happy and clone your example to deploy.
But board can not conect to Wifi 5GHz. 2.4GHz is ok.
Have you any advice me?
Thank you so much!
Trực

**Comment by khoih-prog** [comment]
Thanks for your interest in the library and I'm glad it can help you somehow. The best feature I love in RTL8720DN is its capability to use 5G, instead of over-crowded 2.4G band.

Are you sure you can connect to 2.4GHz? The debug terminal output is always useful to identify the issue.

As you can see in the debug terminal samples, such as [Mqtt_thingstream-on-rtlduino-rtl8720dn](https://github.com/khoih-prog/WiFiWebServer_RTL8720#5-mqtt_thingstream-on-rtlduino-rtl8720dn), I was able to connect to 5G in all of the examples (**HueNet_5G** SSID)

So there is something wrong in you router (5G settings, password length, interference, etc.) and only you can figure out why.

```
Start MQTT_ThingStream on Rtlduino RTL8720DN with RTL8720DN
WiFiWebServer_RTL8720 v1.0.0
Current Firmware Version = 1.0.0
Attempting to connect to SSID: HueNet_5G
Connected! IP address: 192.168.2.152
```

Try step-by-step to isolate the issue.

Good Luck,

**Comment by khoih-prog** [comment]
Hi Trực,

Just created and published a new [**FlashStorage_RTL8720** library](https://github.com/khoih-prog/FlashStorage_RTL8720) for Realtek RTL8720DN, etc. boards.

With this persistent FlashStorage, I'll move on to create new libraries, similar to [**WiFiManager_Generic_Lite**](https://github.com/khoih-prog/WiFiManager_Generic_Lite), [**ESP_WiFiManager_Lite**](https://github.com/khoih-prog/ESP_WiFiManager_Lite) to permit you to store Credentials (WiFi SSID, Password, data, etc.) onto FlashStorage.

Please test, use and report any error / enhancement request there.

Cheers,

KH

**Comment by tmkst2607** [comment]
Thanks for your inform,

I will test it later. But now, Could you please show me the iOS and Android
source code of "Easy Wifi Config" application? I am developing an
Application to connect the board via "BLEWifiConfig"?

Thanks for your advice!
Trực

**Comment by khoih-prog** [comment]
> the iOS and Android source code of "Easy Wifi Config" application

Sorry, I'm not the author of that code.

Good Luck searching,
