### ISSUE TITLE
WiFi.h missing

### ISSUE THREAD

**Issue by xavier862** [khoih-prog/WiFiWebServer_RTL8720#2]
Hi,
I just imported the WiFiWebServer_RTL8720 project to PlatformIO, which immediately complained that `WiFi.h` could not be found.
As I read in `WiFiWebServer_RTL8720.h` a `#warning Use WiFi.h from WiFiWebServer_RTL8720`, I did not attempt to get and use this one: [Seeed_Arduino_rpcWiFi/WiFi.h](https://github.com/Seeed-Studio/Seeed_Arduino_rpcWiFi/blob/master/src/WiFi.h). Should I try it?

Thanks for help !
Xavier

**Comment by khoih-prog** [comment]
Hi,

Thanks for your interest in and opening first issue for this library.

As you know, this library depends on [**AmebaD** core ](https://github.com/ambiot/ambd_arduino) as specified in [**Prerequisites**](https://github.com/khoih-prog/WiFiWebServer_RTL8720#prerequisites).

`WiFi.h` is part of WiFi library provided by the [**AmebaD** core ](https://github.com/ambiot/ambd_arduino) 

You have to install that core in PIO, which I don't know is supporting the [**AmebaD** core ](https://github.com/ambiot/ambd_arduino) yet. Please post on PIO forum to ask for help as necessary.

If you don't have good experience with PIO and still have issue with it, try **Arduino IDE** first, by following the instructions in [**How to add realtek ameba core files**](https://github.com/ambiot/ambd_arduino#how-to-add-realtek-ameba-core-files).

Then moving forward to PIO when testing everything is OK.

Good Luck,

**Comment by khoih-prog** [comment]
Hi @xavier862 

Just created and published a new [**FlashStorage_RTL8720** library](https://github.com/khoih-prog/FlashStorage_RTL8720) for Realtek RTL8720DN, etc. boards.

With this persistent FlashStorage, I'll move on to create new libraries, similar to [**WiFiManager_Generic_Lite**](https://github.com/khoih-prog/WiFiManager_Generic_Lite), [**ESP_WiFiManager_Lite**](https://github.com/khoih-prog/ESP_WiFiManager_Lite) to permit you to store Credentials (WiFi SSID, Password, data, etc.) onto FlashStorage.

Please test, use and report any error / enhancement request there.

Cheers,

KH

**Comment by xavier862** [comment]
Hi [khoih-prog](https://github.com/khoih-prog),
Thanks for this. I'll give it a try, as soon as I am up and running with the RTL8270DN environment (not as user-friendly as ESP32, unfortunately...)
I keep you posted.
Cheers

**Comment by khoih-prog** [comment]
The main reason anyone uses RTL8720DN(BW16) is its support of **5GHz WiFi band**, instead of the over-crowded 2.4GHz band.
This trend will be much more popular in  the near future.

Have a look at [**New and Modified Libraries to support Realtek RTL8720DN(BW16), RTL8722DM and RTL8722CSM**](https://forum.arduino.cc/t/new-and-modified-libraries-to-support-realtek-rtl8720dn-bw16-rtl8722dm-and-rtl8722csm/893977) for the latest updated list.

Some more links to help getting started here

1. [Getting Started with RTL8720DN BW16 Development Board](https://maker.pro/anduino/projects/getting-started-with-rtl8720dn-bw16-development-board)
2. [BW16-RTL8720DN-Module-Arduino](https://github.com/mikey60/BW16-RTL8720DN-Module-Arduino)

Good Luck,
