### ISSUE TITLE
Webserver No Longer Works After Wife Disconnect/Reconnect 

### ISSUE THREAD

**Issue by DarylHenry** [khoih-prog/WiFiWebServer_RTL8720#6]
I am attempting to use a RTL8720dn with your AdvanceWebServer library to allow a client to connect and to the RTL8720dn and control its GPIO pins.  The network the RTL8720dn connects to is hosted via a hotspot.  Sometimes the RTL8720dn may be out of range of the hotspot or sometimes the network make be shut down and then restarted.  The first time a client connects to the webserver on the RTL8720  everything works great.  When RTL8720dn is disconnected from the wireless network and then reconnected the webserver breaks.

I am able to get this code to work on reconnect with a ESP8266 and ESP32 device, but want to use both 2.4 and 5 ghz network that the RTL8720dn offers.  On the ESP8266/ESP32 The software loops though checking to see if there is a wireless connection, and will continue to attempt a connection.  Once the connection is established it calls  server.begin();.  

Can you let me know if I am doing something improperly, or if that functionality just doesn't exist yet?  If it doesn't exist yet are you planning on adding it in soon?

Thanks!

**Comment by khoih-prog** [comment]
Hi @DarylHenry 

Thanks for your interests and usage of the library.

It's totally difficult to investigate from your general and vague descriptions. As you already know, just a wrong line of code can create big issues.

Could you follow the instructions in [**How to report an issue**](https://github.com/khoih-prog/WiFiWebServer_RTL8720/issues/new?assignees=&labels=&template=bug_report.md&title=) and provide more details so that anyone can duplicate the issue you've experienced. Without issue duplication, it's hopeless to investigate and fix the issue, if any.

> both **2.4 and 5 ghz** network

This is the good reason why we need this **RTL8720**

> The network the RTL8720dn connects to is hosted via a hotspot. 

Why do you need a hotspot ? Did you try with normal WiFi network to see if the issue persists? Why don't you use the **AP mode** where the RTL8720 also acts as the WebServer? You then don't need the hotspot anymore.

Anyway, you have to post the code you're using and specify steps how to duplicate the scenario.

I certainly can't be sure if the issue, if real, can be fixed as it's still dependent on too many lower-level layers (libraries, core, etc) not under my control.

**Comment by DarylHenry** [comment]
Hi,

While cleaning up the code to be posted I may have stubbled across a different reason as to why my server and network code are not behaving as expected, and it may have to do with some hang-up that is causing the void loop (); to break.  I am still learning in regards to these microcontrollers so it wouldn't be too surprising for me to do something I should not have.

I really do appreciate your prompt response as well as your dedication to supporting 2.4 and 5 ghz!

Going to close this issue and will open a new more specific issue if needed.
