### ISSUE TITLE
server.hasHeader and server.header both return incorrect values?

### ISSUE THREAD

**Issue by JokinAce** [khoih-prog/WiFiWebServer_RTL8720#8]
### Describe the bug
Trying to get and check value of any Header such as APIKey is not working

### Steps to Reproduce

```
    server.on("/test", []() {
        if (server.hasHeader("APIKey") && server.header("APIKey") == "test")
            server.send(201, "text/plain", "Good");
        else
            server.send(401, "text/plain", "false");
    });
```
Send a GET request with the header "APIKey" and value of "test"

### Expected behavior

Getting a response with status code 201 and text "Good"

### Actual behavior

Getting a response with status code 401 and text "false"

### Screenshots

[Firefox Network analyzer](https://api.alpha-wolf.xyz/files/71jfr12n.png)

### Information
Arduino IDE 2.0.0
AmebaD core 3.1.4

**Comment by khoih-prog** [comment]
Hi @JokinAce 

Please follow the instructions in [**Issue: Bug report**](https://github.com/khoih-prog/WiFiWebServer_RTL8720/issues/new?assignees=&labels=&template=bug_report.md&title=) whenever posting an issue.

Post the [**MRE**](https://stackoverflow.com/help/minimal-reproducible-example), including RTL8720DN code, server code, etc. so that anyone can easily and quickly duplicate the so-called problem you met.

A note is that don't use Arduino IDE **v2.0.0** yet, stick with **v1.8.19** for now.

I'm closing the issue now, and won't reopen until all the requirements are met as well as a bug is somehow proven.
